### ISSUE TITLE
ImportError: cannot import name 'amp' from 'apex'

### ISSUE THREAD

**Issue by amrzv** [lucidrains/reformer-pytorch#154]
Hello.
`setup.sh` fails with the following traceback
```bash
Traceback (most recent call last):
    File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-jwgwyq2j/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-jwgwyq2j/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-jwgwyq2j/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 5, in <module>
  ModuleNotFoundError: No module named 'packaging'
```
![image](https://github.com/lucidrains/reformer-pytorch/assets/36787333/33037461-ab0d-47eb-94a6-4b85abb6e0f5)

And as a result `from apex import amp` fails:
`ImportError: cannot import name 'amp' from 'apex' (unknown location)`

Tested in colab env.
- [Stackoverflow](https://stackoverflow.com/questions/42222096/no-module-named-packaging)
   - `packaging` module is already installed so `pip install packaging` doesn't help
- [issue](https://github.com/NVIDIA/apex/issues/621)

**Comment by pranalidhane** [comment]
Did you solve this? I am facing same problem.
